# -*- coding: utf-8 -*-
"""newton_raphson_for_minimisation.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1ue_m5XGTQdn5bvpubLXLKLyDC1yTpMm1
"""

#sympy library is imported to ease calculations with symbols
from sympy import *   
x = symbols('x')

#The function f is defined along with its first and second derivatives
f = 10*x**2 - 34*x + 45
f1 = f.diff(x)
f2 = f1.diff(x)

#initialisation of a few variables
abs_err = 0.001   #maximum error allowed
max_iter = 10000    #maximum number of iterations allowed
i = 0   #initialising iteration variable i

#x_old denotes the starting value of x given
x_old = 5
err = x_old

#Running the loop to get approximation of the root
#This root acts as the minimum value of the function f(x)
old = x_old

#We run the loop either till the err value becomes less than the maximum allowed
#error value or till we complete max_iter number of iterations
while err >= abs_err and i < max_iter :

  #Calculating the value of first and second derivatives of f at x = old
  f1_val = f1.subs(x, old)
  f2_val = f2.subs(x, old)

  #Preventing division by zero
  if f2_val == 0 :
    break

  #We get a new value of x by applying Newton Raphson method
  x_new = old - f1_val/f2_val

  #Calculating the value of first derivative of f at x = x_new
  newf1_val = f1.subs(x, x_new)

  #updating the variables for the next iteration
  err = abs(newf1_val - f1_val)
  old = x_new
  i += 1
#end while

#Printing the output
print("The function is given by - ")
print(f)
print("\nThe first derivative of the function is given by - ")
print(f1)
print("\nThe second derivative of the function is given by - ")
print(f2)
print("\nWith the starting value as ", x_old, ", the new value is: ")
print (old)

"""With the starting value as  10 , the new value is: 
17/10
With the starting value as  1 , the new value is: 
17/10
With the starting value as  5 , the new value is: 
17/10
With the starting value as  50 , the new value is: 
17/10
With the starting value as  100 , the new value is: 
17/10
With the starting value as  500 , the new value is: 
17/10
With the starting value as  10000 , the new value is: 
17/10
With the starting value as  1000000 , the new value is: 
17/10
"""
